# Generated by Django 4.2.8 on 2023-12-07 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'correo', 'verbose_name_plural': 'correos electrónicos'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'provincia', 'verbose_name_plural': 'provincias'},
        ),
        migrations.AddField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.CharField(max_length=200, verbose_name='direccion de correo'),
        ),
        migrations.AlterField(
            model_name='email',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
