# Generated by Django 4.2.8 on 2023-12-07 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_email_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='imagen a procesar')),
                ('process', models.BooleanField(default=False, verbose_name='procesada')),
            ],
            options={
                'verbose_name': 'Imágen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creación'),
        ),
    ]
