# Generated by Django 4.2.8 on 2023-12-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_images_alter_email_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Emails',
        ),
        migrations.RenameModel(
            old_name='Province',
            new_name='Provinces',
        ),
    ]
