# Generated by Django 4.2.8 on 2023-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_email_emails_rename_province_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='created_at',
            field=models.DateTimeField(verbose_name='fecha de creación'),
        ),
    ]
