# Generated by Django 4.2.8 on 2023-12-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.provinces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provinces'),
        ),
    ]
